### ISSUE TITLE
Error When Flashing 

### ISSUE THREAD

**Issue by launchm** [NabuCasa/universal-silabs-flasher#21]
I have been unable to flash the device and now it will not work at all.
<img width="903" alt="Screenshot 2023-03-21 at 14 51 59" src="https://user-images.githubusercontent.com/2204760/226654830-ee6aabdc-a4b8-458b-9846-b8241d20449b.png">

**Comment by puddly** [comment]
This looks like a bug in the latest release. Can you downgrade and try it again?

```
pip install universal-silabs-flasher==0.0.9
```

**Comment by launchm** [comment]
How can I also force it back to the latest stable release as I might have upgraded it to a beta, If you can help me with the code needed please

**Comment by puddly** [comment]
Run `pip install universal-silabs-flasher==0.0.9`, as I wrote above.

**Comment by launchm** [comment]
Is this to the latest stable version now?

<img width="1103" alt="Screenshot 2023-03-21 at 16 08 41" src="https://user-images.githubusercontent.com/2204760/226669793-8354c27d-da1b-41bf-88fa-2a81a831a9b0.png">

**Comment by puddly** [comment]
Ah. Yes, you've flashed 6.10.3. However, there should be no major differences between 6.10 and 7.2. What prompted you to upgrade then downgrade?

**Comment by launchm** [comment]
I initially was able to use the zigbee to add some devices, I think flashed it but not the radio does not pick anything up. 

Even after this flash to 6.10.3, nothing gets picked up at all. the device gets added, but it like the radio is not seeing any signals out. I have tired to look at logs but nothing jumps out.

I really need some help as I just want to get back to a stable working zigbee radio

**Comment by puddly** [comment]
Can you run an energy scan and post the output? Make sure ZHA is still disabled:

```console
pip install zigpy-cli
zigpy radio --baudrate 115200 ezsp /dev/ttyAMA1 energy-scan --num-scans 20
```

I suspect your Yellow is just in a poor position and needs to be moved away from interference sources (see https://skyconnect.home-assistant.io/connectivity/).

**Comment by launchm** [comment]
![5923C7F2-1E53-42DA-9DE6-68A21D806FB4](https://user-images.githubusercontent.com/2204760/226679620-5ea3a9a9-3af5-4168-be5d-6b5806648267.png)

**Comment by puddly** [comment]
There is something extremely noisy in your environment. Here's a formatted version of your scan results, with a few corrections applied:

```python
 11   5.25% #####
 12   5.89% #####
 13   6.44% ######
 14   7.39% #######
[15] 33.38% #################################
 16   8.18% ########
 17  11.95% ###########
 18  16.58% ################
 19  27.38% ###########################
 20  94.00% #############################################################################################
 21  94.00% #############################################################################################
 22  94.00% #############################################################################################
 23  93.43% #############################################################################################
 24  20.70% ####################
 25  10.34% ##########
 26  43.98% ###########################################
```

Where is your Yellow located? Any nearby devices? Power supplies, other computers, networking equipment, etc.?

**Comment by launchm** [comment]
Moving it to upstairs bedroom (ethernet connected) and not near anything electrical <img width="582" alt="Screenshot 2023-03-21 at 17 28 10" src="https://user-images.githubusercontent.com/2204760/226692549-d2ad5503-f9f1-49a0-8b5e-00c401e0853b.png">

**Comment by launchm** [comment]
left it running for a bit

<img width="550" alt="Screenshot 2023-03-21 at 17 31 42" src="https://user-images.githubusercontent.com/2204760/226693441-c61b31f2-1bf6-4cd7-8275-4f44e5a119fb.png">

**Comment by launchm** [comment]
Entire house WiFi turned off. 
![8E5769CA-4527-4705-82C6-2128C64FD5F8](https://user-images.githubusercontent.com/2204760/226714802-226cf4a7-b6e9-4e86-a4ab-34938525764f.png)

**Comment by puddly** [comment]
That's a very odd noise profile. Are you using the bundled power supply? Or is this PoE? Is there anything plugged into the Yellow?

**Comment by launchm** [comment]
It’s a Poe version, but I am using a power supply which I found. Should I be using a specific one ?

**Comment by puddly** [comment]
That may be the issue. Can you use a different one or PoE?

**Comment by launchm** [comment]
I thought my ASUS router would allow me to use POE, but it does not. 

Is there a spec of the power transformer. I can’t see to find one. At least this way I can ensure the transformer is within the right range.

**Comment by puddly** [comment]
The [product datasheet](https://yellow.home-assistant.io/resources/Yellow_v1.3_Datasheet.pdf) outlines the power supply specs:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/32534428/226736960-f523b870-b7a4-4f9f-9522-18d3cb538780.png">

**Comment by launchm** [comment]
![B753F69C-B915-4034-947F-3E42C04ACC6C](https://user-images.githubusercontent.com/2204760/226749348-f00a5e48-b952-46e9-b1d7-0f17b8aa7072.jpeg)

**Comment by launchm** [comment]
Is this any better, as I tried to add devices via ZHA & Zigbee2MQTT and still nothing

<img width="578" alt="Screenshot 2023-03-22 at 09 23 03" src="https://user-images.githubusercontent.com/2204760/226857817-790b3084-e943-4730-9f65-d3631222e189.png">
<img width="517" alt="Screenshot 2023-03-22 at 09 40 46" src="https://user-images.githubusercontent.com/2204760/226862988-372556b9-2684-417d-834d-ffb14f531e97.png">

**Comment by launchm** [comment]
Hi so what do I need to do, as I can not understand the pull request comments

**Comment by puddly** [comment]
Looks fine as far as I can tell. What device are you unable to add?

**Comment by launchm** [comment]
Aqara Temp sensors, which were all added fine before (well for a day at least). I just seems like it it not picking up any of the 8 I have

**Comment by puddly** [comment]
What change did you make to reduce the noise in the Yellow's environment? It looks much better, and the change to channel 20 should help.

Aqara sensors are somewhat tricky to reset and re-join. Click the "Add Devices" button in ZHA so that the network is opened for joins. Then, hold down the button until the light flashes three times, let go after the third blink, and then just wait. They should join the network after 5-10s. If that doesn't work, pull out their batteries for a few seconds and try again.

**Comment by launchm** [comment]
got it working now, that you so much

**Comment by puddly** [comment]
Great!

So that I can possibly help other people out in the future with similar problems, can you describe what you did to fix the noise issues with the Yellow?

**Comment by launchm** [comment]
So, the original place for the yellow was next to my router. This is not going to be the best place for it, so I will need to try again. I also then switched the power unit to another one. Think it was a combination of things which has made it possible.

**Comment by puddly** [comment]
Interesting. Even when you turned off your WiFi, the noise profile seemed nearly identical so it seems like the root cause was the power plug.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/32534428/226969066-8d66cfdf-e13e-4560-80d9-73d26a1ce284.png">

**Comment by launchm** [comment]
That's what I find crazy, a power plug causing that much havoc. Going to try it again in the same spot with the new power unit
