### ISSUE TITLE
Sonoff ZBDongle-E bootloader reset

### ISSUE THREAD

**Issue by darkxst** [NabuCasa/universal-silabs-flasher#27]
The Sonoff ZBDongle-E has wired up the RTS/DTR lines for resetting into Gecko Bootloader. This is an identical implementation to the auto-downloader circuits commonly found on ESP devkits. For example the following code will enter Gecko even if the app firmware is not responding to the usual probe requests.

https://github.com/espressif/esptool/blob/555458cf7985851a52db35e1893344cc612529cd/esptool/reset.py#L61

Is this something that could be added to this project, in a similar spirit to the yellow gpio reset?

**Comment by puddly** [comment]
Sure, this is supported by PySerial. It's not a high priority at the moment but I will try to get to it eventually.
