### ISSUE TITLE
gpiod api breaks 2.x

### ISSUE THREAD

**Issue by darkxst** [NabuCasa/universal-silabs-flasher#49]
Hey puddly,
  Just a heads up that `gpiod` breaks API with release of v2.x this month, as has switched bindings the offical libgpio. You should probably consider pinning to `1.5.4` for the old behaviour for now.
  
  I will look at porting to the newer version at some point soon, as i plan to implement gpio bootloader reset on some devices too.

**Comment by darkxst** [comment]
Also the new official bindings, bundle a c library which I presume is libgpiod v2.0. However for whatever reason there are no binary wheels available, so required to have a dev environment setup to install this version. Which makes it not very portable.

**Comment by puddly** [comment]
Fixed by #50.
