### ISSUE TITLE
Manual bootloader activation

### ISSUE THREAD

**Issue by darkxst** [NabuCasa/universal-silabs-flasher#52]
Currently if a user for whatever reason has a broken application firmware image and decide to manually enter the bootloader. We probe the bootloader first, but then run the application anyway which will get just get stuck again.

While this is not a huge issue for universal-silabs-flasher, you can always override the probe with `--probe-method bootloader`, there is no way around this when using sl-web-tools.

I wonder if it would be a fair to assume if we probe a bootloader straight up (excluding any case with a bootloader reset switch active), there is quite likely something wrong with the firmware and should continue onto flashing without trying to run and probe the app firmware?

**Comment by puddly** [comment]
You are very right, I think if the bootloader is the first thing to respond, we should assume something is broken and not try to launch the application.
