### ISSUE TITLE
Progress stalled after upload

### ISSUE THREAD

**Issue by robarnold** [NabuCasa/universal-silabs-flasher#57]
My issue looks similar to #3, but occurs when flashing over USB.

Whenever I run `universal-silabs-flasher --verbose --device /dev/ttyACM0 flash --firmware silabs-firmware/Bootloader/NabuCasa_SkyConnect_BL_v2.1.1_115200.gbl` for my SkyConnect, I see [this output](https://gist.github.com/robarnold/694ecb43ed5399c08af93658117dd0ec) and the command does not terminate. It looks like it is stalling just after upload, waiting for the menu to return.

**Comment by robarnold** [comment]
Thank you for the quick fix! Will try it out on the next release to pypi.

**Comment by puddly** [comment]
Thanks! It should be up in a few moments.
