### ISSUE TITLE
Write ieee fails

### ISSUE THREAD

**Issue by AndersDrevin** [NabuCasa/universal-silabs-flasher#64]
Write ieee command fails on sonoff dongle-e. If I change row 320 in flasher.py from "if not await ezsp.can_write_custom_eui64" to "if not await ezsp.can_rewrite_custom_eui64" it works.

**Comment by puddly** [comment]
This command is deprecated and will be removed. Setting the IEEE address is done with other methods in newer SDK releases.

**Comment by Taraman17** [comment]
And how is it done then currently?

**Comment by pmarques** [comment]
> And how is it done then currently?

I just hacked `flasher.py` and commented out the entire if condition/block.

**Comment by pmarques** [comment]
You can also follow this steps https://github.com/NabuCasa/universal-silabs-flasher/issues/55#issuecomment-1872267142
